In [1]:
import googlemaps
gmaps = googlemaps.Client(key='AIzaSyD3DeaatuQqGlFZTgKEpX7G9l-LH85Ky1k')
geocode_result = gmaps.geocode('Chinatown, Philadelphia, PA')

In [2]:
from googlemaps.places import places_autocomplete_session_token
key = 'AIzaSyD3DeaatuQqGlFZTgKEpX7G9l-LH85Ky1k'
client = googlemaps.Client(key)
location = (geocode_result[0]['geometry']['location']['lat'], geocode_result[0]['geometry']['location']['lng'])
ty = 'school'
language = 'Chinese'
radius = 10000

In [3]:
schools = gmaps.places_nearby(location=location, keyword='school', open_now=True,
                                  rank_by='distance', type=ty)

In [4]:
import pandas as pd
import numpy as np
name = []
lat = []
lng = []

for i in schools.get('results'):
    name.append(i['name'])
    lat.append(i['geometry']['location']['lat'])
    lng.append(i['geometry']['location']['lng'])
    
schoolsDf = pd.DataFrame({"name": name, "lat": lat, "lng": lng})
schoolsDf

                                                 name        lat        lng
0                        Freire Charter Middle School  39.951510 -75.157753
1                        Commonwealth Charter Academy  39.956488 -75.160238
2   Book Worms Early Learning Center Child Care Sc...  39.956112 -75.144197
3   kelly educational staffing philadelphia school...  39.961024 -75.162782
4                           Gen. Philip Kearny School  39.963871 -75.148157
5         Primrose School of Center City Philadelphia  39.953292 -75.168060
6        John W. Hallahan Catholic Girls’ High School  39.959874 -75.169877
7                        Russell Byers Charter School  39.955705 -75.171711
8                             Spanish Language School  39.951242 -75.173898
9                      Greene Towne Montessori School  39.956167 -75.175392
10                Christopher Columbus Charter School  39.938579 -75.158640
11                    Philadelphia Technicians School  39.972751 -75.167638
12                                 Philly Free School  39.941384 -75.176060
13                                     Girard College  39.973398 -75.171228
14                                    The City School  39.971618 -75.176424
15          AAA School of Trucking Philadephia Campus  39.970425 -75.128903
16          Dean Office at the Fox School of Business  39.980244 -75.155830